name: Quality Assurance

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run shared setup
        uses: ./.github/actions/setup

      - name: Run lint
        run: make lint
